[tool.poetry]
name = "mayainsights"
version = "0.1.0"
description = ""
authors = ["Jay <iasonas.tr@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
pandas = "1.4.2"
requests = "2.27.1"
python-decouple = "3.6"
backoff = "2.0.1"
google-cloud-bigquery = "3.3.2"
googleads = "33.0.0"
google-ads = "18.1.0"
google-api-python-client = "2.49.0"
bingads = "13.0.14"
facebook-business = "14.0.0"
google-cloud-storage = "2.5.0"
oauth2client = "4.1.3"
simplejson = "3.17.2"
pyfarmhash = "0.2.2"
psycopg2 = "2.9.3"
dj-database-url = "0.5.0"
Django = "3.0.8"
SQLAlchemy = "1.4.37"
hvac = "0.10.5"
Jinja2 = "2.11.2"
MarkupSafe = "1.1.1"
arrow = "1.1.0"
httplib2 = "0.20.4"
mysql-connector-python = "8.0.28"
openpyxl = "3.0.9"
fasttext = "0.9.2"
redis = "3.5.2"
msal = "1.12.0"
fastapi = "0.79.0"
beautifulsoup4 = "4.11.1"
slack-sdk = "3.18.1"
playwright = "1.23.1"
Unidecode = "1.3.4"
nltk = "3.7"
rake-nltk = "1.0.6"
tldextract = "3.3.1"
selenium = "4.4.3"
gcsfs = "2022.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
